### PR TITLE
 README.md

### PR DESCRIPTION
**Pull request by BRIYANITER**
imano is incharge of website
Bobby is incharge of Figma
Ammar is incharge of User Manual
rishi will assist all and take care of video presentation

### CODE REVIEW

**Comment by S5nses** [comment]
sure bro no problem

**Comment by S5nses** [comment]
> imano is incharge of website Bobby is incharge of Figma Ammar is incharge of User Manual rishi will assist all and take care of video presentation

ill send it asap

**Comment by S5nses** [comment]
guys the link for the user manual is attached below.

https://www.canva.com/design/DAGRvnJ0BVI/0YcM7xUMNU0ZSrgeBjDhlQ/view?utm_content=DAGRvnJ0BVI&utm_campaign=designshare&utm_medium=link&utm_source=editor

**Comment by BRIYANITER** [comment]
> guys the link for the user manual is attached below.
> 
> https://www.canva.com/design/DAGRvnJ0BVI/0YcM7xUMNU0ZSrgeBjDhlQ/view?utm_content=DAGRvnJ0BVI&utm_campaign=designshare&utm_medium=link&utm_source=editor

well done cha

**Comment by imano-web** [comment]
> imano is incharge of website Bobby is incharge of Figma Ammar is incharge of User Manual rishi will assist all and take care of video presentation

noted cha im done.. sending now

**Comment by imano-web** [comment]
https://imanhafizi1704.wixsite.com/tasteoftraditions

**Comment by BRIYANITER** [comment]
https://www.figma.com/proto/sw9DQ2rSZ78KlGZiL341kE/Taste-of-Tradition?page-id=1%3A2&node-id=701-771&node-type=canvas&viewport=-1893%2C-4045%2C0.72&t=ZnqHQluqJ6GY7DDI-1&scaling=min-zoom&content-scaling=fixed


guys the above is from bobby

**Comment by BRIYANITER** [comment]
i guess our work here is done.

**Pull request closed without merging**
